image:
- Visual Studio 2015

test_script:
    - npm install titanium -g
    - ti sdk install 6.2.0.v20170822113609 -d
    - cd windows
    - ti build -p windows --build-only --run-cmake

build: off

artifacts:
  - path: windows\*.zip
    name: MyApp
